name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run --rm --volume=$PWD:/srv/jekyll:Z jekyll/jekyll:latest jekyll build
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo '${{ secrets.sshkey }}' > ~/.ssh/id_ed25519
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no decal@ssh.ocf.berkeley.edu "mkdir -p /home/d/de/decal/public_html" && rsync -avzpce "ssh -o StrictHostKeyChecking=no" --del _site/ --exclude static --exclude archives decal@ssh.ocf.berkeley.edu:/home/d/de/decal/public_html
