name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run --rm jekyll/jekyll:latest jekyll build
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Deploy site to tsunami
      run: |
        echo '${{ secrets.sshkey }}' | ssh -i /dev/stdin -o StrictHostKeyChecking=no decal@ssh.ocf.berkeley.edu "mkdir -p ~/$(DEPLOY_DIR)" && rsync -avzpce "ssh -o StrictHostKeyChecking=no" --del _site/ --exclude static --exclude archives decal@ssh.ocf.berkeley.edu:$(DEPLOY_DIR)
